env: "local"
storage_path: "./scheduler/scheduler.db"
http_server:
  address: "localhost:8082"
  timeout: 5s
db:
  host: localhost
  port: 5432
  name: short_db
  user: postgres
  password: postgres
  schema: postgres